### ISSUE TITLE
Convert to Python3

### ISSUE THREAD

**Issue by jwowillo** [jwowillo/pacmanplus#2]
Convert all code to python3. Ensure all existing functionality remains working.

The advantages of doing this are:
- The larger python3 community will be able to work in the repository.
- pyc files won't litter the source directories.
- Several classes implemented in the source directory which don't need to can be removed (Counter).

**Comment by ejw0013** [comment]
2to3 script in python 3 appears to work flawlessly, at least with prints and exceptions.

**Comment by ejw0013** [comment]
Finished
